---
title: "Surface Area Calculations from Wax Dipping"
author: "HM Putnam"
date: "2/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

## install packages if you dont already have them
if (!require("tidyverse")) install.packages("tidyverse")

# load packages
library(tidyverse)
```

```{r}
#Surface area by wax dipping Veal et al 

Data <- read.csv("data/timepoint_0/0_surface_area/0_surface_area_data.csv", header=TRUE)

Stnds <- read.csv("data/timepoint_0/0_surface_area/wax.standards.csv", header=TRUE)
Stnds$delta.mass.g <- Stnds$weight2.g-Stnds$weight1.g

stnd.curve <- lm(surface.area.cm2~delta.mass.g, data=Stnds)
plot(surface.area.cm2~delta.mass.g, data=Stnds)

stnd.curve$coefficients

Data$delta.mass.g <- Data$weight2.g-Data$weight1.g
Data$surface.area.cm2 <- stnd.curve$coefficients[2] * Data$delta.mass.g + stnd.curve$coefficients[1]
# Coral sample metadata
metadata <- read_csv("metadata/coral_metadata.csv") %>% select(1:3)

Data <- full_join(Data, metadata, by="colony_id")

Data <- Data%>% filter(species=="Acropora")

Data%>%
  mutate(timepoint="timepoint0")%>%
  select(colony_id, surface.area.cm2, timepoint)%>%
  write_csv("output/0_surface_area.csv")



```


